// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abbklujvzxhoyvlfnvlp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiYmtsdWp2enhob3l2bGZudmxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MzY2NjYsImV4cCI6MjA3MDQxMjY2Nn0.lD2-iAu2_vE1x_hf36Wr2R-9clbrUGxK8Z-eOuFK8j0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});